id: help-bot-agent
name: help-bot-agent
description: Help Bot Agent
resources:
  models: []
  knowledge: []
entryNode: start
graph:
  nodes:
    start:
      type: input
      mode: cli
      output: user_input
    check_exit:
      type: function
      runtime: typescript
      functionName: checkExit
      input:
        - user_input
      output: should_exit
    run_module:
      type: module
      module: help-bot-module
      inputs:
        user_input1: user_input
      outputs:
        module_output: response
    output:
      type: output
      mode: cli
      input: response
  edges:
    - from: start
      to: check_exit
    - from: check_exit
      to: run_module
      condition:
        input: should_exit
        key: continue
    - from: check_exit
      to: __end__
      condition:
        input: should_exit
        key: exit
    - from: run_module
      to: output
    - from: output
      to: __end__
